aptcacher:
  restart: always
  image: dockerregistry.zetcom.local/ops/apt-cacher
  ports:
    - 3142:3142
  volumes:
    - /var/cache/apt-cacher-ng:/var/cache/apt-cacher-ng
    - /var/log/apt-cacher-ng:/var/log/apt-cacher-ng
